blank_issues_enabled: false
contact_links:
  - name: Ask a question or get help
    url: https://github.com/stenvanhouwelingen/innova-climate/discussions
    about: Please ask questions and get configuration/wiring help in GitHub Discussions instead of opening issues.
